import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {initialState,ensurePlan,migrateState,eat,addDay,monday,mainIngredient,FIXED_NG,matches} from '../dist/model.js';
const menus=JSON.parse(readFileSync(new URL('../dist/data/menus.json',import.meta.url)));
const week=(s,d,list=menus)=>Array.from({length:7},(_,i)=>ensurePlan(s,addDay(monday(d),i),list).menuId);
test('52 weeks have seven unique allowed dishes and no adjacent repeats',()=>{const s=initialState();let previous;for(let w=0;w<52;w++){const ids=week(s,addDay('2026-09-14',w*7));assert.equal(new Set(ids).size,7);assert.notEqual(ids[0],previous);previous=ids[6];for(const id of ids){const m=menus.find(m=>m.id===id);assert.ok(!FIXED_NG.some(t=>matches(m,t)));}}});
test('history, ratings, checks, date browsing order and reload cannot change plan',()=>{const a=initialState(),b=initialState(),expected=week(a,'2026-09-14');for(const i of [6,2,0,5,1,4,3]){const d=addDay('2026-09-14',i);ensurePlan(b,d,menus);b.history[d]={menuId:menus[i].id,rating:'like'};b.checks[d]={0:true};b.excluded={'2026-09-14':menus.map(m=>m.id)};}assert.deepEqual(week(JSON.parse(JSON.stringify(b)),'2026-09-14'),expected);b.family[0].dislike=['魚'];assert.deepEqual(week(b,'2026-09-14'),expected);});
test('old repeated and skipped plans migrate once preserving actual history and family',()=>{const s=initialState();delete s.plannerVersion;s.plans={'2026-09-14':{status:'skipped'},'2026-09-15':{status:'planned',menuId:'menu_01'}};s.history={'2026-09-14':{menuId:'menu_01',rating:'like'}};s.checks={'2026-09-15':{0:true}};s.excluded={old:['menu_01']};const history=structuredClone(s.history);migrateState(s);assert.deepEqual(s.plans,{});assert.deepEqual(s.checks,{});assert.deepEqual(s.history,history);assert.equal(s.excluded,undefined);const ids=week(s,'2026-09-14');assert.equal(new Set(ids).size,7);s.checks['2026-09-15']={0:true};migrateState(s);assert.ok(s.checks['2026-09-15'][0]);});
test('NG aliases match ingredients and spicy or bitter attributes',()=>{for(const [tag,ingredient] of [['レンコン','れんこん'],['辛い物','豆板醤'],['苦い物','ゴーヤ'],['ししゃも','シシャモ'],['ピーマン','ピーマン']])assert.ok(matches({tags:[],ingredients:[{name:ingredient}],seasonings:[]},tag));});
test('short candidate list leaves empty days instead of duplicates',()=>{const s=initialState(),allowed=menus.filter(m=>!FIXED_NG.some(t=>matches(m,t))).slice(0,3);const ids=week(s,'2026-09-14',allowed);assert.equal(ids.filter(Boolean).length,3);assert.equal(new Set(ids.filter(Boolean)).size,3);s.family[0].ng=allowed.flatMap(m=>m.tags);assert.equal(week(s,'2026-09-14',allowed).filter(Boolean).length,0);});
test('NG change rebuilds whole week without stale ingredient checks',()=>{const s=initialState(),before=week(s,'2026-09-14');s.family[0].ng=['豚肉','鶏肉'];for(let i=0;i<7;i++)s.checks[addDay('2026-09-14',i)]={0:true};const after=week(s,'2026-09-14');assert.equal(new Set(after).size,7);after.forEach((id,i)=>{assert.ok(!menus.find(m=>m.id===id).tags.some(t=>['豚肉','鶏肉'].includes(t)));if(before[i]!==id)assert.equal(s.checks[addDay('2026-09-14',i)],undefined);});});
test('cannot replace historical dish silently after rebuilding',()=>{const s=initialState();ensurePlan(s,'2026-09-01',menus);s.history['2026-09-01']={menuId:'different',rating:'like'};assert.throws(()=>eat(s,'2026-09-01'));});
test('pass controls and handlers removed',()=>{for(const f of ['dist/app.js','dist/index.html','dist/model.js'])assert.ok(!/skipDay|data-skip|skip-form|skip-dialog/.test(readFileSync(f,'utf8')));});
test('static assets, PWA and 68 complete recipes',()=>{assert.equal(menus.length,68);assert.equal(new Set(menus.map(m=>m.id)).size,68);for(const m of menus){assert.ok(m.time<=30);assert.ok(m.steps.length<=5);assert.equal(m.servings,3);assert.ok(m.ingredients.length&&m.tags.length);}const manifest=JSON.parse(readFileSync('dist/manifest.json'));for(const i of manifest.icons)assert.ok(existsSync('dist/'+i.src));for(const name of ['index.html','app.js','model.js','style.css','service-worker.js','data/menus.json','data/fruits.json'])assert.ok(existsSync('dist/'+name));});

test('primary ingredient never repeats across 52 weeks and beef appears once per fortnight',()=>{const s=initialState();let previous;for(let w=0;w<52;w++){const ids=week(s,addDay('2026-09-14',w*7));const groups=ids.map(id=>mainIngredient(menus.find(m=>m.id===id)));for(const group of groups){assert.notEqual(group,previous);previous=group;}assert.equal(groups.filter(g=>g==='beef').length,w%2);}});
test('ingredient rotation still respects exclusions over week boundaries',()=>{const s=initialState();s.family[0].ng=['牛肉','豚肉'];let previous;for(let w=0;w<10;w++){const ids=week(s,addDay('2026-09-14',w*7));for(const id of ids){if(!id){previous=undefined;continue;}const group=mainIngredient(menus.find(m=>m.id===id));assert.notEqual(group,previous);assert.ok(!['beef','pork'].includes(group));previous=group;}}});

test('chicken then pork is allowed but meat in disguised dishes is classified',()=>{const sample=(name)=>({tags:[],ingredients:[{name}],seasonings:[]});for(const name of ['鶏ひき肉','鶏むね肉','ささみ'])assert.equal(mainIngredient(sample(name)),'chicken');for(const name of ['豚ひき肉','ハム','ウインナー'])assert.equal(mainIngredient(sample(name)),'pork');assert.equal(mainIngredient(sample('牛乳')),'vegetable');const s=initialState(),groups=week(s,'2026-09-21').map(id=>mainIngredient(menus.find(m=>m.id===id)));assert.ok(groups.some((g,i)=>g==='chicken'&&groups[i+1]==='pork'));});
test('one remaining ingredient group leaves gaps including at week boundaries',()=>{const s=initialState(),pool=menus.filter(m=>mainIngredient(m)==='chicken');let previous;for(let w=0;w<4;w++)for(const id of week(s,addDay('2026-09-14',w*7),pool)){assert.ok(!id||!previous);previous=id;}});
test('v3 saved repetitions are rebuilt while actual meals remain unchanged',()=>{const s=initialState();s.plannerVersion=3;s.plans={'2026-09-14':{status:'planned',menuId:'menu_02'},'2026-09-15':{status:'planned',menuId:'menu_08'}};s.history={'2026-09-14':{menuId:'menu_02',rating:'like'}};const history=structuredClone(s.history);const ids=week(s,'2026-09-14');assert.equal(s.plannerVersion,4);assert.deepEqual(s.history,history);assert.notEqual(mainIngredient(menus.find(m=>m.id===ids[0])),mainIngredient(menus.find(m=>m.id===ids[1])));});
